name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Nutzt ein stabiles Ubuntu-System

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: System-Abhängigkeiten installieren
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev
        sudo apt-get install -y lld cmake
        pip install --upgrade pip
        pip install Cython==0.29.33 buildozer virtualenv

    - name: APK mit Buildozer bauen
      run: |
        buildozer -v android debug
      env:
        # Umgeht den Node-Fehler auf den GitHub-Servern
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    - name: APK Datei speichern
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-Quest-APK
        path: ./bin/*.apk

